//group 등록하기
POST http://localhost:3000/api/groups
Content-Type: application/json

{
	"name": "kaiiis",
	"password": "12kim",
	"imageUrl": "image.png",
	"isPublic": true,
	"introduction": "first blog"
}

//group 조회하기
###
Get http://localhost:3000/api/groups?keyword=kaiiis&isPublic=true

###
POST http://localhost:3000/api/groups/27/verify-password
Content-Type : application/json

{
  "password": "12kim"
}

###
//group 공개 여부 확인
GET http://localhost:3000/api/groups/12/is-public

###
//group 수정 여부 확인
PATCH http://localhost:3000/api/groups/36
Content-Type : application/json

{
	"name": "string",
	"password": "12kim",
	"imageUrl": "string",
  "introduction": "string",
	"isPublic": false
}
###
DELETE http://localhost:3000/api/groups/33
Content-Type : application/json

{
	"password": "12kim"
}