//post 등록하기
POST http://localhost:3000/api/groups/2/posts
Content-Type: application/json

{
	"nickname": "kllsdfdsfsdfsdm",
	"title": "telc",
	"content": "ffffxxf",
	"postPassword": "password1234",
	"groupPassword": "password123456",
	"imageUrl": "string",
	"tags": [ "tel", "100등"],
	"location": "string",
	"moment": "2024-02-21",
	"isPublic": true
}

###
//post 조회하기
GET http://localhost:3000/api/groups/2/posts?keyword=tel&isPublic=false

###
//비밀번호 확인
POST http://localhost:3000/api/posts/39/verify-password
Content-Type : application/json

{
  "password": "password1234"
}

###
//post 공개 여부 확인
GET http://localhost:3000/api/posts/42/is-public